// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"blog/internal/repository"
	"blog/pkg/config"
	"blog/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateService(cf string, rpo repository.Repository) (Service, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := logger.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.New(options)
	if err != nil {
		return nil, err
	}
	serviceService := NewService(zapLogger, rpo)
	return serviceService, nil
}

// wire.go:

var ServiceProviderSet = wire.NewSet(logger.ProviderSet, config.ProviderSet, ProviderSet)
