// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"admin/pkg/config"
	"admin/pkg/database/es"
	"admin/pkg/database/mongo"
	"admin/pkg/database/postgres"
	"admin/pkg/database/redis"
	"admin/pkg/logger"
	"admin/pkg/mq/kafka"
	"admin/pkg/trace"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateRepository(f string) (Repository, error) {
	viper, err := config.New(f)
	if err != nil {
		return nil, err
	}
	options, err := logger.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.New(options)
	if err != nil {
		return nil, err
	}
	postgresOptions, err := postgres.NewOptions(viper, zapLogger)
	if err != nil {
		return nil, err
	}
	db, err := postgres.New(postgresOptions)
	if err != nil {
		return nil, err
	}
	redisOptions, err := redis.NewOptions(viper, zapLogger)
	if err != nil {
		return nil, err
	}
	redisDB, err := redis.New(redisOptions)
	if err != nil {
		return nil, err
	}
	esOptions, err := es.NewOptions(viper, zapLogger)
	if err != nil {
		return nil, err
	}
	client, err := es.New(esOptions)
	if err != nil {
		return nil, err
	}
	mongoOptions, err := mongo.NewOptions(viper, zapLogger)
	if err != nil {
		return nil, err
	}
	mongoDB, err := mongo.New(mongoOptions)
	if err != nil {
		return nil, err
	}
	repositoryRepository := NewRepository(zapLogger, db, redisDB, client, mongoDB)
	return repositoryRepository, nil
}

// wire.go:

var repositoryProviderSet = wire.NewSet(logger.ProviderSet, config.ProviderSet, mongo.ProviderSet, postgres.ProviderSet, es.ProviderSet, redis.ProviderSet, trace.ProviderSet, kafka.ProviderSet, ProviderSet)
