definitions:
  response.Data:
    properties:
      code:
        description: 自定义返回码  0:表示正常
        type: integer
      data:
        description: 返回的具体数据
      message:
        description: 关于这次响应的说明信息
        type: string
      meta:
        description: 数据meta
      namespace:
        description: 异常的范围
        type: string
      reason:
        description: 异常原因
        type: string
      recommend:
        description: 推荐链接
        type: string
      request_id:
        description: 请求Id
        type: string
      type:
        description: 数据类型, 可以缺省
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/advert:
    get:
      consumes:
      - application/json
      description: 广告列表接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Data'
      summary: 广告列表
  /api/v1/advert/{id}:
    get:
      consumes:
      - application/json
      description: 广告详情接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Data'
      summary: 广告详情
  /api/v1/captcha:
    get:
      consumes:
      - application/json
      description: 获取登陆验证码接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Data'
      summary: 验证码
swagger: "2.0"
